version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12
        environment:
          - GO111MODULE=on
          - GITHUB_TOKEN=${GITHUB_TOKEN}
    working_directory: /go/src/github.com/oleiade/trousseau

jobs:
  build:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - run: go build github.com/oleiade/trousseau/cmd/...
      - run: go test github.com/oleiade/trousseau/...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  release:
    executor: go
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires: 
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/